<?php
include_once("utilerias.php");
$calcula = new utilerias();
$tsecundarias = array("Sin especificar","General","Tecnica","Abierta","Telesecundaria");
$vtsecundarias = array("0","1","2","3","4","5");
echo "<html>";
echo "  <body>";
echo "  <center><h1>L A Y O U T</h1></center><br>";
echo "      <form action='accion.php' method='GET'>";
echo "          <select name='ecivil'>";
echo "              <option value='00'>Sin especificarlo";
echo "              <option value='01'>Soltero";
echo "              <option value='02'>Casado";
echo "              <option value='03'>Union libre";
echo "              <option value='04'>Divorciado";
echo "              <option value='05'>Viudo";
echo "          </select><br><br>";
echo "          Tipo de secundaria";
$calcula->paraselect("tsecundarias",0,$tsecundarias, $vtsecundarias);
echo "          <br><br>";
echo "          <select name='carrera'>";
echo "              <option value='00'>Sin especificarlo";
echo "              <option value='01'>Administracion de Recursos Humanos";
echo "              <option value='02'>Electronica";
echo "              <option value='03'>Mecanica Industrial";
echo "              <option value='04'>Programacion";
echo "              <option value='05'>Soporte y mantenimiento de equipo de computo";
echo "              <option value='06'>Mecatronica";
echo "          </select><br>";
echo "          <select name='regimen'>";
echo "              <option value='00'>Sin definir";
echo "              <option value='01'>Publico Federal";
echo "              <option value='02'>Publico Estatal";
echo "              <option value='03'>Privado";
echo "          </select><br>";
echo "          <br><input type='submit' name='procesos' value='enviar'>";
echo "      </form>";
echo "  </body>";
echo " </html>";
?>